pub mod app_error;
pub mod app_state;
pub mod book;
pub mod book_assets;
pub mod book_format;
pub mod book_load_info;
pub mod book_metadata;
pub mod bookmark;
pub mod chapter;
pub mod enums;
pub mod paragraph;
pub mod paragraph_kind;
pub mod reader_settings;
pub mod reading_mode;
pub mod reading_progress;
pub mod recent_book_item;
pub mod search_enums;
pub mod search_query;
pub mod search_result;
pub mod search_state;
pub mod theme_kind;
pub mod toc_item;
pub mod ui_state;

pub use app_error::{AppError, AppResult};
pub use app_state::AppState;
pub use book::Book;
pub use book_assets::BookAssets;
pub use book_format::BookFormat;
pub use book_load_info::BookLoadInfo;
pub use book_metadata::BookMetadata;
pub use bookmark::Bookmark;
pub use chapter::Chapter;
pub use enums::{LeftPanelTab, ScreenKind};
pub use paragraph::Paragraph;
pub use paragraph_kind::ParagraphKind;
pub use reader_settings::ReaderSettings;
pub use reading_mode::ReadingMode;
pub use reading_progress::ReadingProgress;
pub use recent_book_item::RecentBookItem;
pub use search_enums::SearchScope;
pub use search_query::SearchQuery;
pub use search_result::SearchResult;
pub use search_state::SearchState;
pub use theme_kind::ThemeKind;
pub use toc_item::TocItem;
pub use ui_state::UiState;

pub mod error_codes {
    pub const FILE_NOT_FOUND: &str = "FILE_NOT_FOUND";
    pub const FILE_OPEN_FAILED: &str = "FILE_OPEN_FAILED";
    pub const UNSUPPORTED_FORMAT: &str = "UNSUPPORTED_FORMAT";
    pub const EPUB_CONTAINER_MISSING: &str = "EPUB_CONTAINER_MISSING";
    pub const EPUB_OPF_MISSING: &str = "EPUB_OPF_MISSING";
    pub const EPUB_TOC_PARSE_FAILED: &str = "EPUB_TOC_PARSE_FAILED";
    pub const EPUB_METADATA_PARSE_FAILED: &str = "EPUB_METADATA_PARSE_FAILED";
    pub const TXT_DECODE_FAILED: &str = "TXT_DECODE_FAILED";
    pub const CONTENT_EMPTY: &str = "CONTENT_EMPTY";
    pub const SETTINGS_LOAD_FAILED: &str = "SETTINGS_LOAD_FAILED";
    pub const SETTINGS_SAVE_FAILED: &str = "SETTINGS_SAVE_FAILED";
    pub const PROGRESS_LOAD_FAILED: &str = "PROGRESS_LOAD_FAILED";
    pub const PROGRESS_SAVE_FAILED: &str = "PROGRESS_SAVE_FAILED";
    pub const BOOKMARK_SAVE_FAILED: &str = "BOOKMARK_SAVE_FAILED";
    pub const RECENT_SAVE_FAILED: &str = "RECENT_SAVE_FAILED";
}
